#!/bin/bash

sudo chmod +x -R run_all.sh scripts/*

echo -en "Verifying required packages\n"

if [ -f /etc/redhat-release ]; then
        sudo yum install dependencies/rpms/* --nogpgcheck -y
fi

if [ ! -d /usr/local/aws ]; then
	unzip dependencies/rpms/awscli-bundle.zip
	./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
	rm -rf "awscli-bundle"
fi

if [ -f certificates/Citi_DEVELOPMENT_chain.pem ]; then
  sudo cp certificates/Citi_DEVELOPMENT_chain.pem /etc/pki/ca-trust/source/
  sudo update-ca-trust extract
fi

virtualenv --no-site-packages --distribute virtualenv
virtualenv/bin/pip install --upgrade pip --no-index --find-links="dependencies/pip/"
virtualenv/bin/pip install setuptools==32.3.1 --no-index --find-links="dependencies/pip/"
virtualenv/bin/pip install -r requirements.txt --no-index --find-links="dependencies/pip/"
virtualenv/bin/python setup.py develop

pip install -r requirements-local.txt --no-index --find-links="dependencies/pip/"

echo -en "Build complete\n"