#!/bin/sh
set -e


if [ ! -f /etc/yum.repos.d/localrepo.repo ]; then
sudo mkdir -p /usr/localrepo/
sudo cp -vn ./devtools/* /usr/localrepo/
sudo cp -vn ./localrepo.repo /etc/yum.repos.d/localrepo.repo
sudo createrepo -v /usr/localrepo/
sudo yum-config-manager --enable localrepo
sudo yum clean all
sudo yum update
fi

if [ -f /etc/redhat-release ]; then
    for package in s3cmd libevent libgcrypt-devel libgpg-error-devel libxml2 libxml2-devel libxml2-python libxslt-devel perl-Data-Dumper perl-srpm-macros perl-Test-Harness perl-Thread-Queue perl-XML-LibXML perl-XML-Parser perl-XML-SAX perl-XML-SAX-Base perl-XML-Simple python-devel python-docs python-javapackages python-magic python-setuptools python-virtualenv xml-commons-apis xml-commons-resolver xz-devel zlib-devel ; do
        if [ "$(rpm -qa $package 2>/dev/null)" = "" ]; then
            missing="${missing:+$missing }$package"
        fi
    done
    if [ -n "$missing" ]; then
        echo "$missing"
	echo "$0: missing required RPM packages. Installing via sudo." 1>&2
        sudo yum install -y $missing
    fi
fi

virtualenv --no-site-packages --distribute virtualenv

./virtualenv/bin/pip install --no-index --find-links="./piprepo" -r requirements.txt

./virtualenv/bin/python setup.py develop

if [ ! -f ~/.s3cfg ]; then
    echo "s3cmd not configured.\n$USER# s3cmd --configure" && exit 0
fi


