#!/bin/sh

mkdir -p output

sudo chmod +x run_all.sh scripts/*

sudo yum install dependencies/rpms/* --nogpgcheck -y

virtualenv --no-site-packages --distribute virtualenv
virtualenv/bin/pip install --upgrade pip --no-index --find-links="dependencies/pip/"
virtualenv/bin/pip install setuptools --no-index --find-links="dependencies/pip/"
virtualenv/bin/pip install -r requirements.txt --no-index --find-links="dependencies/pip/"
virtualenv/bin/python setup.py develop

sudo cp certificates/Citi_DEVELOPMENT_chain.pem /etc/pki/ca-trust/source/
sudo update-ca-trust extract
